"""Add profile slug and bio

Revision ID: 4acdbf1cd2c0
Revises: 404dab57395c
Create Date: 2026-04-28 03:07:06.465032

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op  # type: ignore
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4acdbf1cd2c0"
down_revision: Union[str, Sequence[str], None] = "404dab57395c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_log_user_type"), table_name="email_log")
    op.drop_table("email_log")
    op.add_column(
        "admin_audit_log",
        sa.Column("timestamp", sa.DateTime(), server_default="now()", nullable=False),
    )
    op.alter_column(
        "admin_audit_log",
        "actor_role",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "admin_audit_log",
        "resource_type",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_constraint(
        op.f("admin_audit_log_actor_id_fkey"), "admin_audit_log", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "admin_audit_log", "users", ["actor_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("admin_audit_log", "created_at")
    op.drop_index(op.f("idx_attempts_group_user"), table_name="attempts")
    op.drop_index(op.f("idx_coding_attempts_user"), table_name="coding_attempts")
    op.add_column(
        "mentor_comments", sa.Column("coding_attempt_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "mentor_comments", "attempt_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(
        None,
        "mentor_comments",
        "coding_attempts",
        ["coding_attempt_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("idx_notifications_user_read"), table_name="notifications")
    op.drop_column("notifications", "expires_at")
    op.drop_column("question_banks", "created_by_role")
    op.add_column(
        "user_roles", sa.Column("scope_type", sa.String(length=20), nullable=False)
    )
    op.add_column("user_roles", sa.Column("scope_id", sa.Integer(), nullable=True))
    op.drop_constraint(op.f("uq_user_role"), "user_roles", type_="unique")
    op.create_unique_constraint(
        "uq_user_scoped_role",
        "user_roles",
        ["user_id", "role", "scope_type", "scope_id"],
    )
    op.add_column(
        "users", sa.Column("cover_photo_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "users", sa.Column("custom_slug", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("bio", sa.Text(), nullable=True))
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.create_index(op.f("ix_users_custom_slug"), "users", ["custom_slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_custom_slug"), table_name="users")
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.drop_column("users", "bio")
    op.drop_column("users", "custom_slug")
    op.drop_column("users", "cover_photo_url")
    op.drop_constraint("uq_user_scoped_role", "user_roles", type_="unique")
    op.create_unique_constraint(op.f("uq_user_role"), "user_roles", ["user_id", "role"])
    op.drop_column("user_roles", "scope_id")
    op.drop_column("user_roles", "scope_type")
    op.add_column(
        "question_banks",
        sa.Column(
            "created_by_role", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "notifications",
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("idx_notifications_user_read"), "notifications", ["user_id"], unique=False
    )
    op.drop_constraint(None, "mentor_comments", type_="foreignkey")
    op.alter_column(
        "mentor_comments", "attempt_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("mentor_comments", "coding_attempt_id")
    op.create_index(
        op.f("idx_coding_attempts_user"), "coding_attempts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_attempts_group_user"), "attempts", ["user_id"], unique=False
    )
    op.add_column(
        "admin_audit_log",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text(
                "'2026-04-07 08:40:19.89265+00'::timestamp with time zone"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "admin_audit_log", type_="foreignkey")
    op.create_foreign_key(
        op.f("admin_audit_log_actor_id_fkey"),
        "admin_audit_log",
        "users",
        ["actor_id"],
        ["id"],
    )
    op.alter_column(
        "admin_audit_log",
        "resource_type",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "admin_audit_log",
        "actor_role",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("admin_audit_log", "timestamp")
    op.create_table(
        "email_log",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "email_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "to_email", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "sent_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "success",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("email_log_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_log_pkey")),
    )
    op.create_index(
        op.f("ix_email_log_user_type"),
        "email_log",
        ["user_id", "email_type", "sent_at"],
        unique=False,
    )
    # ### end Alembic commands ###
