"""structural_rbac_and_profile_expansion

Revision ID: 843de3af2081
Revises: ce2a0eb9a698
Create Date: 2026-04-27 20:53:59.490935

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op  # type: ignore
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "843de3af2081"
down_revision: Union[str, Sequence[str], None] = "ce2a0eb9a698"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_log_id"), table_name="email_log")
    op.drop_table("email_log")
    op.drop_index(
        op.f("ix_group_course_subscriptions_id"),
        table_name="group_course_subscriptions",
    )
    op.drop_table("group_course_subscriptions")
    op.drop_index(op.f("idx_attempts_group_user"), table_name="attempts")
    op.add_column("groups", sa.Column("vertical_id", sa.Integer(), nullable=True))
    op.add_column("groups", sa.Column("department_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "groups", "departments", ["department_id"], ["id"])
    op.create_foreign_key(None, "groups", "verticals", ["vertical_id"], ["id"])
    op.drop_index(op.f("idx_notifications_user_read"), table_name="notifications")
    op.add_column(
        "users",
        sa.Column(
            "expertise_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("users", sa.Column("vertical_id", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("department_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.create_foreign_key(None, "users", "verticals", ["vertical_id"], ["id"])
    op.create_foreign_key(None, "users", "departments", ["department_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.drop_column("users", "department_id")
    op.drop_column("users", "vertical_id")
    op.drop_column("users", "expertise_json")
    op.create_index(
        op.f("idx_notifications_user_read"),
        "notifications",
        ["user_id", "is_read"],
        unique=False,
    )
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.drop_column("groups", "department_id")
    op.drop_column("groups", "vertical_id")
    op.create_index(
        op.f("idx_attempts_group_user"), "attempts", ["user_id"], unique=False
    )
    op.create_table(
        "group_course_subscriptions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("course_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("assigned_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "assigned_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text(
                "'2026-04-27 15:03:12.520148+00'::timestamp with time zone"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("group_course_subscriptions_course_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("group_course_subscriptions_group_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("group_course_subscriptions_pkey")),
        sa.UniqueConstraint("group_id", "course_id", name=op.f("uq_group_course")),
    )
    op.create_index(
        op.f("ix_group_course_subscriptions_id"),
        "group_course_subscriptions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "email_log",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "recipient_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "email_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "sent_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text(
                "'2026-04-27 15:03:12.520148+00'::timestamp with time zone"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "success",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("email_log_pkey")),
    )
    op.create_index(op.f("ix_email_log_id"), "email_log", ["id"], unique=False)
    # ### end Alembic commands ###
