"""add quick_references to question bank

Revision ID: 872a4a801e1e
Revises: d5605dca9802
Create Date: 2026-04-16 20:11:46.694370

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op  # type: ignore
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "872a4a801e1e"
down_revision: Union[str, Sequence[str], None] = "d5605dca9802"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assignments", sa.Column("max_attempts", sa.Integer(), nullable=True))
    op.add_column(
        "assignments", sa.Column("is_compulsory", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "question_banks",
        sa.Column(
            "quick_references", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_constraint(
        op.f("question_banks_course_id_fkey"), "question_banks", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "question_banks", "courses", ["course_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("question_discussions_parent_id_fkey"),
        "question_discussions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "question_discussions",
        "question_discussions",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "question_discussions", type_="foreignkey")
    op.create_foreign_key(
        op.f("question_discussions_parent_id_fkey"),
        "question_discussions",
        "question_discussions",
        ["parent_id"],
        ["id"],
    )
    op.drop_constraint(None, "question_banks", type_="foreignkey")
    op.create_foreign_key(
        op.f("question_banks_course_id_fkey"),
        "question_banks",
        "courses",
        ["course_id"],
        ["id"],
    )
    op.drop_column("question_banks", "quick_references")
    op.drop_column("assignments", "is_compulsory")
    op.drop_column("assignments", "max_attempts")
    # ### end Alembic commands ###
