"""Add missing schemas

Revision ID: ce2a0eb9a698
Revises: 47ecb64695b8
Create Date: 2026-04-27 19:10:52.170732

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op  # type: ignore
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce2a0eb9a698"
down_revision: Union[str, Sequence[str], None] = "47ecb64695b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role", name="uq_user_role"),
    )
    op.create_index(op.f("ix_user_roles_id"), "user_roles", ["id"], unique=False)
    op.add_column(
        "assignments", sa.Column("created_by_role", sa.String(length=20), nullable=True)
    )
    # Use server_default so existing rows don't fail NOT NULL constraint
    op.add_column(
        "assignments",
        sa.Column(
            "assignment_type",
            sa.String(length=20),
            server_default="quiz",
            nullable=False,
        ),
    )
    op.add_column(
        "assignments",
        sa.Column(
            "visibility_scope",
            sa.String(length=20),
            server_default="group",
            nullable=False,
        ),
    )
    op.add_column(
        "coding_attempts",
        sa.Column(
            "leaderboard_eligible", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "coding_attempts", sa.Column("rank_computation", sa.Integer(), nullable=True)
    )
    op.add_column(
        "question_banks",
        sa.Column(
            "visibility_scope",
            sa.String(length=20),
            server_default="group",
            nullable=False,
        ),
    )
    op.add_column(
        "question_banks",
        sa.Column("subscriber_groups", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.add_column(
        "users", sa.Column("profile_photo_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "users", sa.Column("intro_video_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "users", sa.Column("github_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("linkedin_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("leetcode_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("codolio_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("streak_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("last_active_date", sa.DateTime(timezone=True), nullable=True),
    )

    # --- Performance indexes ---
    op.create_index("idx_attempts_group_user", "attempts", ["user_id"], unique=False)
    op.create_index(
        "idx_notifications_user_read",
        "notifications",
        ["user_id", "is_read"],
        unique=False,
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)

    # --- New tables ---
    op.create_table(
        "email_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_email", sa.String(length=255), nullable=False),
        sa.Column("email_type", sa.String(length=50), nullable=False),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column("success", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_log_id"), "email_log", ["id"], unique=False)

    op.create_table(
        "group_course_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "course_id", name="uq_group_course"),
    )
    op.create_index(
        op.f("ix_group_course_subscriptions_id"),
        "group_course_subscriptions",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_active_date")
    op.drop_column("users", "streak_count")
    op.drop_column("users", "codolio_url")
    op.drop_column("users", "leetcode_url")
    op.drop_column("users", "linkedin_url")
    op.drop_column("users", "github_url")
    op.drop_column("users", "intro_video_url")
    op.drop_column("users", "profile_photo_url")
    op.drop_column("question_banks", "subscriber_groups")
    op.drop_column("question_banks", "visibility_scope")
    op.drop_column("coding_attempts", "rank_computation")
    op.drop_column("coding_attempts", "leaderboard_eligible")
    op.drop_column("assignments", "visibility_scope")
    op.drop_column("assignments", "assignment_type")
    op.drop_column("assignments", "created_by_role")
    op.drop_index(op.f("ix_user_roles_id"), table_name="user_roles")
    op.drop_table("user_roles")
    # ### end Alembic commands ###
