"""v3_baseline

Revision ID: d5605dca9802
Revises:
Create Date: 2026-04-07 12:36:03.062850

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op  # type: ignore
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5605dca9802"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_dept_name_per_org"),
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "verticals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verticals_id"), "verticals", ["id"], unique=False)
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vertical_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vertical_id"],
            ["verticals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_batches_id"), "batches", ["id"], unique=False)
    op.create_table(
        "vertical_courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vertical_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vertical_id"],
            ["verticals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vertical_id", "course_id", name="uq_vertical_course"),
    )
    op.create_index(
        op.f("ix_vertical_courses_id"), "vertical_courses", ["id"], unique=False
    )
    op.create_table(
        "admin_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("actor_role", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_audit_log_id"), "admin_audit_log", ["id"], unique=False
    )
    op.create_table(
        "coding_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=30), nullable=False),
        sa.Column("expected_approach", sa.Text(), nullable=True),
        sa.Column("sample_solution", sa.Text(), nullable=False),
        sa.Column("evaluation_criteria", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("concept_tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("hint_1", sa.Text(), nullable=True),
        sa.Column("hint_2", sa.Text(), nullable=True),
        sa.Column("hint_3", sa.Text(), nullable=True),
        sa.Column("max_hints_allowed", sa.Integer(), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("is_compulsory", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coding_questions_id"), "coding_questions", ["id"], unique=False
    )
    op.create_table(
        "mentor_group_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mentor_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mentor_id", "group_id", name="uq_mentor_group"),
    )
    op.create_index(
        op.f("ix_mentor_group_assignments_id"),
        "mentor_group_assignments",
        ["id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("link_type", sa.String(length=30), nullable=True),
        sa.Column("link_id", sa.Integer(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_id", sa.Integer(), nullable=True),
        sa.Column("coding_question_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("passing_score_percent", sa.Integer(), nullable=True),
        sa.Column("lock_after_due", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bank_id"], ["question_banks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["coding_question_id"],
            ["coding_questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assignments_id"), "assignments", ["id"], unique=False)
    op.create_table(
        "coding_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coding_question_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("submitted_code", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=30), nullable=False),
        sa.Column("overall_result", sa.String(length=20), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "rubric_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column("time_taken_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["coding_question_id"], ["coding_questions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coding_attempts_id"), "coding_attempts", ["id"], unique=False
    )
    op.create_index(
        "ix_coding_attempts_question_user",
        "coding_attempts",
        ["coding_question_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "assignment_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("best_score", sa.Integer(), nullable=True),
        sa.Column("attempts_used", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignment_completions_id"),
        "assignment_completions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "daily_challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("challenge_date", sa.Date(), nullable=False),
        sa.Column("selection_reason", sa.String(length=255), nullable=True),
        sa.Column("is_mentor_override", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "group_id", "challenge_date", name="uq_daily_challenge_group_date"
        ),
    )
    op.create_index(
        op.f("ix_daily_challenges_id"), "daily_challenges", ["id"], unique=False
    )
    op.create_table(
        "mentor_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("mentor_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mentor_comments_id"), "mentor_comments", ["id"], unique=False
    )
    op.create_table(
        "question_discussions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("bank_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("upvotes", sa.Integer(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["bank_id"], ["question_banks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["question_discussions.id"],
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_discussions_id"), "question_discussions", ["id"], unique=False
    )
    op.create_table(
        "question_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_reports_id"), "question_reports", ["id"], unique=False
    )
    op.alter_column(
        "ai_cache",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "attempts",
        sa.Column(
            "is_daily_challenge",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column("attempts", "bank_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("attempts", "score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("attempts", "total", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "attempts",
        "is_anonymous",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "attempts",
        "is_reviewed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "attempts",
        "attempted_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("ix_attempts_bank_id", "attempts", ["bank_id"], unique=False)
    op.create_index(
        "ix_attempts_bank_user", "attempts", ["bank_id", "user_id"], unique=False
    )
    op.create_index(op.f("ix_attempts_id"), "attempts", ["id"], unique=False)
    op.create_index("ix_attempts_user_id", "attempts", ["user_id"], unique=False)
    op.drop_constraint(op.f("attempts_bank_id_fkey"), "attempts", type_="foreignkey")
    op.create_foreign_key(None, "attempts", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        None, "attempts", "question_banks", ["bank_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "courses", sa.Column("description", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "courses", sa.Column("icon_slug", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "courses",
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    op.alter_column(
        "courses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("courses_group_id_fkey"), "courses", type_="foreignkey")
    op.drop_column("courses", "group_id")
    op.add_column("groups", sa.Column("batch_id", sa.Integer(), nullable=True))
    op.add_column(
        "groups",
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    op.alter_column(
        "groups",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(None, "groups", "batches", ["batch_id"], ["id"])
    op.drop_column("groups", "group_admin_id")
    op.add_column(
        "question_banks",
        sa.Column(
            "bank_type",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'practice'"),
        ),
    )
    op.add_column(
        "question_banks", sa.Column("max_attempts_per_day", sa.Integer(), nullable=True)
    )
    op.add_column(
        "question_banks", sa.Column("max_total_attempts", sa.Integer(), nullable=True)
    )
    op.add_column(
        "question_banks",
        sa.Column(
            "retake_policy",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'all_count'"),
        ),
    )
    op.add_column(
        "question_banks",
        sa.Column(
            "lock_after_due",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "question_banks",
        sa.Column(
            "is_org_public",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "question_banks", sa.Column("cloned_from_bank_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "question_banks",
        "difficulty",
        existing_type=sa.TEXT(),
        type_=sa.String(length=20),
        nullable=False,
    )
    op.alter_column(
        "question_banks",
        "created_by",
        existing_type=sa.TEXT(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="NULL",
    )
    op.alter_column(
        "question_banks",
        "time_per_question",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("30"),
    )
    op.alter_column(
        "question_banks",
        "show_timer",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "question_banks",
        "shuffle",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "question_banks",
        "allow_descriptive",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "question_banks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_question_banks_id"), "question_banks", ["id"], unique=False
    )
    op.create_foreign_key(None, "question_banks", "courses", ["course_id"], ["id"])
    op.create_foreign_key(
        None, "question_banks", "question_banks", ["cloned_from_bank_id"], ["id"]
    )
    op.create_foreign_key(None, "question_banks", "users", ["created_by"], ["id"])
    op.add_column(
        "questions",
        sa.Column(
            "has_code", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "questions", sa.Column("code_language", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "questions",
        sa.Column("concept_tags", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column(
            "report_count", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "questions",
        sa.Column(
            "needs_review",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column("questions", "bank_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "questions",
        "difficulty",
        existing_type=sa.TEXT(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "questions",
        "user_description",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.create_index("ix_questions_bank_id", "questions", ["bank_id"], unique=False)
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.alter_column(
        "resources",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "is_active")
    op.alter_column(
        "resources",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_index("ix_questions_bank_id", table_name="questions")
    op.alter_column(
        "questions",
        "user_description",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "questions",
        "difficulty",
        existing_type=sa.String(length=20),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column("questions", "bank_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("questions", "needs_review")
    op.drop_column("questions", "report_count")
    op.drop_column("questions", "concept_tags")
    op.drop_column("questions", "code_language")
    op.drop_column("questions", "has_code")
    op.drop_constraint(None, "question_banks", type_="foreignkey")
    op.drop_constraint(None, "question_banks", type_="foreignkey")
    op.drop_constraint(None, "question_banks", type_="foreignkey")
    op.drop_index(op.f("ix_question_banks_id"), table_name="question_banks")
    op.alter_column(
        "question_banks",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "question_banks",
        "allow_descriptive",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "question_banks",
        "shuffle",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "question_banks",
        "show_timer",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "question_banks",
        "time_per_question",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("30"),
    )
    op.alter_column(
        "question_banks",
        "created_by",
        existing_type=sa.Integer(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "question_banks",
        "difficulty",
        existing_type=sa.String(length=20),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.drop_column("question_banks", "cloned_from_bank_id")
    op.drop_column("question_banks", "is_org_public")
    op.drop_column("question_banks", "lock_after_due")
    op.drop_column("question_banks", "retake_policy")
    op.drop_column("question_banks", "max_total_attempts")
    op.drop_column("question_banks", "max_attempts_per_day")
    op.drop_column("question_banks", "bank_type")
    op.add_column(
        "groups",
        sa.Column("group_admin_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.alter_column(
        "groups",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("groups", "is_active")
    op.drop_column("groups", "batch_id")
    op.add_column(
        "courses",
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("courses_group_id_fkey"), "courses", "groups", ["group_id"], ["id"]
    )
    op.alter_column(
        "courses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("courses", "is_active")
    op.drop_column("courses", "icon_slug")
    op.drop_column("courses", "description")
    op.drop_constraint(None, "attempts", type_="foreignkey")
    op.drop_constraint(None, "attempts", type_="foreignkey")
    op.create_foreign_key(
        op.f("attempts_bank_id_fkey"), "attempts", "question_banks", ["bank_id"], ["id"]
    )
    op.drop_index("ix_attempts_user_id", table_name="attempts")
    op.drop_index(op.f("ix_attempts_id"), table_name="attempts")
    op.drop_index("ix_attempts_bank_user", table_name="attempts")
    op.drop_index("ix_attempts_bank_id", table_name="attempts")
    op.alter_column(
        "attempts",
        "attempted_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "attempts",
        "is_reviewed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "attempts",
        "is_anonymous",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("attempts", "total", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("attempts", "score", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("attempts", "bank_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("attempts", "is_daily_challenge")
    op.alter_column(
        "ai_cache",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_question_reports_id"), table_name="question_reports")
    op.drop_table("question_reports")
    op.drop_index(op.f("ix_question_discussions_id"), table_name="question_discussions")
    op.drop_table("question_discussions")
    op.drop_index(op.f("ix_mentor_comments_id"), table_name="mentor_comments")
    op.drop_table("mentor_comments")
    op.drop_index(op.f("ix_daily_challenges_id"), table_name="daily_challenges")
    op.drop_table("daily_challenges")
    op.drop_index(
        op.f("ix_assignment_completions_id"), table_name="assignment_completions"
    )
    op.drop_table("assignment_completions")
    op.drop_index("ix_coding_attempts_question_user", table_name="coding_attempts")
    op.drop_index(op.f("ix_coding_attempts_id"), table_name="coding_attempts")
    op.drop_table("coding_attempts")
    op.drop_index(op.f("ix_assignments_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_mentor_group_assignments_id"), table_name="mentor_group_assignments"
    )
    op.drop_table("mentor_group_assignments")
    op.drop_index(op.f("ix_coding_questions_id"), table_name="coding_questions")
    op.drop_table("coding_questions")
    op.drop_index(op.f("ix_admin_audit_log_id"), table_name="admin_audit_log")
    op.drop_table("admin_audit_log")
    op.drop_index(op.f("ix_vertical_courses_id"), table_name="vertical_courses")
    op.drop_table("vertical_courses")
    op.drop_index(op.f("ix_batches_id"), table_name="batches")
    op.drop_table("batches")
    op.drop_index(op.f("ix_verticals_id"), table_name="verticals")
    op.drop_table("verticals")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
