"""Add missing kt project fields  [NEUTRALIZED — was destructive]

Revision ID: d887cd121a07
Revises: 65543201ec49
Create Date: 2026-07-06 20:13:11.923173

DO NOT RESTORE THE ORIGINAL BODY OF THIS REVISION.

Despite its name, the autogenerated body of this revision did not add any fields.
It issued `op.drop_table(...)` for **54 tables**, including `users`,
`organizations`, `attempts`, `questions`, `groups`, `batches`, `kt_projects` and
`refresh_tokens` — i.e. essentially the entire application schema. Running
`alembic upgrade head` against production would have destroyed the database.

This is the signature of `alembic revision --autogenerate` run with an incomplete
model import: alembic compared the live database against a metadata object that
knew about almost no tables, concluded every table had been deleted, and emitted
drops for all of them. (Its `downgrade()` correspondingly re-created those tables,
which is why the file was ~1000 lines.)

It is neutralized rather than deleted so the revision graph
(65543201ec49 -> d887cd121a07) stays intact and any environment already stamped at
this revision remains consistent.

If genuine "missing kt project fields" changes are ever needed, add them as a NEW
revision — never by reinstating this body.
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d887cd121a07"
down_revision: Union[str, Sequence[str], None] = "65543201ec49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Intentionally a no-op. See the module docstring."""
    pass


def downgrade() -> None:
    """Intentionally a no-op. See the module docstring."""
    pass
