"""add manual verification fields

Revision ID: e4dd00a47382
Revises: 843de3af2081
Create Date: 2026-04-27 20:56:38.615355

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "e4dd00a47382"
down_revision: Union[str, Sequence[str], None] = "843de3af2081"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attempts",
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("attempts", sa.Column("comment", sa.Text(), nullable=True))
    op.add_column(
        "coding_attempts",
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("coding_attempts", sa.Column("comment", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coding_attempts", "comment")
    op.drop_column("coding_attempts", "is_verified")
    op.drop_column("attempts", "comment")
    op.drop_column("attempts", "is_verified")
    # ### end Alembic commands ###
